DROP DATABASE IF EXISTS library;
DROP USER IF EXISTS admin;
CREATE USER admin WITH PASSWORD '1';
CREATE database library
WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE library TO PUBLIC;
GRANT ALL ON DATABASE library TO admin;

GRANT ALL PRIVILEGES ON DATABASE "library" to admin;
